In [1]:
#Question no.1

In [4]:
import numpy as np
ar = np.arange(2,51,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [5]:
#Question no.2

In [6]:
import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

5
9
7
8
6
3
4
1
2
0
[5 9 7 8 6 3 4 1 2 0]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
#Question no.3

In [8]:
import numpy as np
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)

2
9


In [9]:
#Question no.4

In [10]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


In [11]:
#Question no.5

In [12]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2)))

[[0.30659421 0.78806734 0.54176598]
 [0.6517506  0.37306109 0.35578488]
 [0.97425362 0.20388351 0.26748754]
 [0.82826487 0.89591237 0.17151546]
 [0.03763247 0.17573443 0.31689198]
 [0.43546535 0.77970046 0.09795179]]

[[0.30659421 0.78806734 0.54176598 0.82826487 0.89591237 0.17151546]
 [0.6517506  0.37306109 0.35578488 0.03763247 0.17573443 0.31689198]
 [0.97425362 0.20388351 0.26748754 0.43546535 0.77970046 0.09795179]]


In [13]:
#Question no.6

In [14]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3]))
